services:
  postgres-document-manager-db:
    image: "postgres:latest"
    container_name: postgres-document-manager-db
    expose:
      - "5434"
    ports:
      - "5434:5434"
    environment:
      POSTGRES_DB: document-manager
      POSTGRES_USER: betmart
      POSTGRES_PASSWORD: betmart
      PGPORT: 5434
    volumes:
      - postgres-document-manager-db:/var/lib/postgresql/document-manager/data
volumes:
  postgres-document-manager-db:
    driver: local